import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Mic,Square,Upload,Search,FileText,ListChecks,Clock,Trash2,Download,ShieldCheck,Play,Pause,Share2,Plus,Tag,Star,X,Archive,BarChart3,CalendarPlus,Copy,Folder,Mail,Printer,RotateCcw,Wifi,WifiOff,Settings,Cloud,Database,Smartphone,Sun,Moon,Monitor,Home,CalendarDays,CheckSquare2,Bell,ChevronLeft}from'lucide-react';
import'./styles.css';
import'./mobile.css';

type TranscriptSegment={speaker:string;text:string;start:number;end:number};type ActionItem={task:string;owner?:string|null;due?:string|null;priority?:'low'|'medium'|'high'};type Meeting={id:string;title:string;date:string;duration:number;transcript:string;transcriptSegments?:TranscriptSegment[];speakerNames?:Record<string,string>;summary:string;actions:string[];actionDetails?:ActionItem[];keyPoints?:string[];decisions?:string[];topics?:string[];followUp?:string[];openQuestions?:string[];risks?:string[];meetingType?:string;language?:string;tags?:string[];completed?:boolean[];favorite?:boolean;audio?:string;attendees?:string;agenda?:string;folder?:string;status?:'planned'|'complete';archived?:boolean;notes?:string;followupEmail?:string};
const seed:Meeting[]=[{id:'welcome',title:'Welcome to Said and Done',date:new Date().toISOString(),duration:0,language:'auto',transcript:'Record a meeting or import an audio file. Your recordings and notes stay on this device.',summary:'A private workspace that turns conversations into clear summaries, decisions, and action items.',actions:['Record your first meeting'],}];
const storeKey='meeting-notes-v1';
const load=():Meeting[]=>{try{const saved:Meeting[]=JSON.parse(localStorage.getItem(storeKey)||'null')||seed;return saved.map(meeting=>meeting.id==='welcome'&&['Welcome to SaidDone','Welcome to Meeting Notes'].includes(meeting.title)?{...meeting,title:'Welcome to Said and Done'}:meeting)}catch{return seed}};
const summarize=(text:string)=>{const clean=(text.match(/[^.!?\n]+[.!?]?/g)||[]).map(s=>s.replace(/^\s*(speaker\s*\d+|[A-Z][a-z]+):\s*/i,'').trim()).filter(s=>s.length>2);if(!clean.length)return{summary:'No transcript is available yet.',actions:[]};const stop=new Set('the a an and or but to of in on for with is are was were be been it this that we i you they he she our your their from at as by about so just really have has had do did can could would'.split(' '));const freq=new Map<string,number>();clean.join(' ').toLowerCase().match(/[a-z][a-z\x27-]{2,}/g)?.forEach(w=>{if(!stop.has(w))freq.set(w,(freq.get(w)||0)+1)});const topics=[...freq.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([w])=>w);const actionPattern=/\b(?:i|we|you|they|he|she|[A-Z][a-z]+)\s+(?:will|need(?:s)? to|should|must|plan(?:s)? to|agreed to|is going to|are going to)\b|^(?:please\s+)?(?:send|review|complete|schedule|confirm|check|update|create|prepare|call|email|share|follow up|finish|submit|assign|contact)\b|\b(?:due|deadline|by (?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|tomorrow|next week|\w+ \d{1,2}))\b/i;const decisionPattern=/\b(decided|agreed|approved|selected|confirmed|finalized|will proceed|moving forward)\b/i;const actions=clean.filter(s=>actionPattern.test(s)).slice(0,8);const decisions=clean.filter(s=>decisionPattern.test(s)).slice(0,4);const scored=clean.map((s,i)=>({s,i,score:(s.toLowerCase().match(/[a-z][a-z\x27-]{2,}/g)||[]).reduce((n,w)=>n+(freq.get(w)||0),0)/Math.max(5,s.split(/\s+/).length)})).filter(x=>!actions.includes(x.s)).sort((a,b)=>b.score-a.score||a.i-b.i).slice(0,3).sort((a,b)=>a.i-b.i).map(x=>x.s);const parts=[`Overview: The meeting focused on ${topics.length?topics.join(', '):'the topics captured in the transcript'}.`,scored.length?`Key points:\n${scored.map(s=>'• '+s).join('\n')}`:'',decisions.length?`Decisions:\n${decisions.map(s=>'• '+s).join('\n')}`:'No explicit decisions were identified.',actions.length?`Follow-up: ${actions.length} action item${actions.length===1?'':'s'} identified.`:'No explicit follow-up assignments were identified.'];return{summary:parts.filter(Boolean).join('\n\n'),actions}};
const fmt=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
const localDateTime=(iso:string)=>{const d=new Date(iso);const offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,16)};
const safeName=(name:string)=>name.replace(/[\\/:*?"<>|]+/g,'-').trim()||'meeting-notes';
const SB_URL='https://bazjlrualnmbanmhiuau.supabase.co';const SB_KEY='sb_publishable_ez3TVctnbFIUHqr_dMOUeQ_5WpsYEHs';type Session={access_token:string;refresh_token:string;user:{id:string;email?:string}};const sessionKey='meeting-notes-session';const loadSession=():Session|null=>{try{return JSON.parse(localStorage.getItem(sessionKey)||'null')}catch{return null}};

type Theme='system'|'light'|'dark';
type MobileTab='conversations'|'calendar'|'actions';
type MobileHomeProps={meetings:Meeting[];query:string;tab:MobileTab;onQuery:(value:string)=>void;onTab:(tab:MobileTab)=>void;onOpenMeeting:(id:string)=>void;onRecord:()=>void;onSchedule:()=>void;onSettings:()=>void};
const dateHeading=(iso:string)=>{const date=new Date(iso),today=new Date(),yesterday=new Date();yesterday.setDate(today.getDate()-1);const same=(a:Date,b:Date)=>a.toDateString()===b.toDateString();if(same(date,today))return'Today';if(same(date,yesterday))return'Yesterday';return date.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})};
function MobileHome({meetings,query,tab,onQuery,onTab,onOpenMeeting,onRecord,onSchedule,onSettings}:MobileHomeProps){
 const active=meetings.filter(m=>!m.archived&&m.id!=='welcome');
 const visible=active.filter(m=>(m.title+' '+m.summary+' '+m.transcript).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>+new Date(b.date)-+new Date(a.date));
 const groups=visible.reduce<Record<string,Meeting[]>>((all,meeting)=>{const key=dateHeading(meeting.date);(all[key]||=[]).push(meeting);return all},{});
 const actions=active.flatMap(meeting=>meeting.actions.map((task,index)=>({meeting,task,index,done:!!meeting.completed?.[index]}))).filter(item=>!item.done);
 const agenda=active.filter(m=>m.status==='planned').sort((a,b)=>+new Date(a.date)-+new Date(b.date));
 return <section className="mobile-home"><header className="home-top"><div className="wordmark" aria-label="Said and Done"><img src="/saiddone-mark.png" alt=""/><b>Said and Done</b></div><div className="home-actions"><button aria-label="Search conversations" onClick={()=>document.getElementById('mobile-search')?.focus()}><Search/></button><button aria-label="Schedule a meeting" onClick={onSchedule}><Plus/></button><button aria-label="Notifications"><Bell/></button></div></header><nav className="home-tabs" aria-label="Meeting views"><button className={tab==='conversations'?'active':''} onClick={()=>onTab('conversations')}>Conversations</button><button className={tab==='calendar'?'active':''} onClick={()=>onTab('calendar')}>Calendar</button><button className={tab==='actions'?'active':''} onClick={()=>onTab('actions')}>Action items</button></nav>
  {tab==='conversations'?<div className="home-content"><div className="home-filter"><Search/><input id="mobile-search" aria-label="Search conversations" placeholder="Search conversations" value={query} onChange={e=>onQuery(e.target.value)}/></div>{Object.keys(groups).length?Object.entries(groups).map(([label,items])=><section className="conversation-group" key={label}><h2>{label}</h2>{items.map(meeting=><button className="conversation-row" key={meeting.id} onClick={()=>onOpenMeeting(meeting.id)}><span className="conversation-avatar"><Mic/></span><span className="conversation-card"><b>{meeting.title}</b><small>{new Date(meeting.date).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · {fmt(meeting.duration)}</small>{meeting.summary&&<p>{meeting.summary.replace(/\n/g,' ').slice(0,150)}</p>}</span></button>)}</section>):<div className="home-empty"><span><Mic/></span><h2>Your conversations live here</h2><p>Record or import a meeting to create your first set of notes.</p><button onClick={onRecord}><Mic/> Start recording</button></div>}</div>:tab==='calendar'?<div className="home-content"><div className="view-heading"><span>My agenda</span><button onClick={onSchedule}><Plus/> Add meeting</button></div>{agenda.length?<section className="agenda-list"><h2>Upcoming</h2>{agenda.map(meeting=><button key={meeting.id} onClick={()=>onOpenMeeting(meeting.id)}><span><b>{meeting.title}</b><small>{new Date(meeting.date).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></span><CalendarDays/></button>)}</section>:<div className="home-empty"><span><CalendarDays/></span><h2>Your agenda is clear</h2><p>Scheduled meetings will appear here.</p><button onClick={onSchedule}><Plus/> Schedule a meeting</button></div>}</div>:<div className="home-content">{actions.length?<><div className="view-heading"><span>Open action items</span><small>{actions.length} remaining</small></div><section className="action-list">{actions.map(({meeting,task,index})=><button key={meeting.id+index} onClick={()=>onOpenMeeting(meeting.id)}><span className="action-check"/><span><b>{task}</b><small>{meeting.title}</small></span></button>)}</section></>:<div className="home-empty"><span><CheckSquare2/></span><h2>No open action items</h2><p>Tasks from your meeting summaries will appear here.</p></div>}</div>}
  <nav className="app-nav" aria-label="Mobile navigation"><button className={tab==='conversations'?'active':''} onClick={()=>onTab('conversations')}><Home/><span>Home</span></button><button onClick={()=>onTab('calendar')}><CalendarDays/><span>Calendar</span></button><button className="record-orb" onClick={onRecord} aria-label="Record a meeting"><Mic/></button><button onClick={()=>onTab('actions')}><CheckSquare2/><span>Actions</span></button><button onClick={onSettings}><Settings/><span>Account</span></button></nav>
 </section>
}
type SettingsPanelProps={open:boolean;onClose:()=>void;session:Session|null;email:string;password:string;authMode:'signin'|'signup';cloudStatus:string;online:boolean;installAvailable:boolean;theme:Theme;autoSync:boolean;onEmail:(value:string)=>void;onPassword:(value:string)=>void;onAuthMode:()=>void;onAuthenticate:()=>void;onSync:()=>void;onSignOut:()=>void;onBackup:()=>void;onRestore:(event:React.ChangeEvent<HTMLInputElement>)=>void;onInstall:()=>void;onTheme:(theme:Theme)=>void;onAutoSync:(enabled:boolean)=>void};
function SettingsPanel({open,onClose,session,email,password,authMode,cloudStatus,online,installAvailable,theme,autoSync,onEmail,onPassword,onAuthMode,onAuthenticate,onSync,onSignOut,onBackup,onRestore,onInstall,onTheme,onAutoSync}:SettingsPanelProps){
 const panel=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null;panel.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('keydown',key);document.body.classList.add('settings-visible');return()=>{document.removeEventListener('keydown',key);document.body.classList.remove('settings-visible');previous?.focus()}},[open,onClose]);
 if(!open)return null;
 return <div className="settings-layer"><button className="settings-backdrop" aria-label="Close settings" onClick={onClose}/><div className="settings-panel" ref={panel} role="dialog" aria-modal="true" aria-labelledby="settings-title" tabIndex={-1}><div className="settings-header"><div><span className="eyebrow">Your workspace</span><h2 id="settings-title">Settings</h2></div><button className="icon-button" onClick={onClose} aria-label="Close settings"><X/></button></div><div className="settings-content">
  <section className="settings-section"><div className="settings-section-heading"><Cloud/><div><h3>Account and cloud sync</h3><p>Keep your meeting library available across your devices.</p></div></div>{session?<div className="account-card"><div className="account-avatar">{session.user.email?.slice(0,1).toUpperCase()||'M'}</div><div><b>{session.user.email}</b><small>Protected cloud account</small></div><span className="status-pill">Connected</span></div>:<div className="auth-form"><label>Email<input type="email" autoComplete="email" placeholder="you@example.com" value={email} onChange={e=>onEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={authMode==='signup'?'new-password':'current-password'} placeholder="At least 8 characters" value={password} onChange={e=>onPassword(e.target.value)}/></label></div>}<div className="settings-actions">{session?<><button className="primary-action" onClick={onSync}>Sync now</button><button className="secondary-action" onClick={onSignOut}>Sign out</button></>:<><button className="primary-action" onClick={onAuthenticate} disabled={!email||password.length<8}>{authMode==='signup'?'Create account':'Sign in'}</button><button className="secondary-action" onClick={onAuthMode}>{authMode==='signin'?'Create an account':'I already have an account'}</button></>}</div>{cloudStatus&&<p className="inline-status">{cloudStatus}</p>}<label className="setting-row"><span><b>Automatic sync</b><small>Sync after your meeting library changes.</small></span><input className="switch" type="checkbox" checked={autoSync} onChange={e=>onAutoSync(e.target.checked)}/></label></section>
  <section className="settings-section"><div className="settings-section-heading"><Monitor/><div><h3>Appearance</h3><p>Choose how Said and Done looks on this device.</p></div></div><div className="theme-picker" role="radiogroup" aria-label="Color theme">{([['system',Monitor,'System'],['light',Sun,'Light'],['dark',Moon,'Dark']] as const).map(([value,Icon,label])=><button key={value} className={theme===value?'active':''} role="radio" aria-checked={theme===value} onClick={()=>onTheme(value)}><Icon/>{label}</button>)}</div></section>
  <section className="settings-section"><div className="settings-section-heading"><Database/><div><h3>Data and storage</h3><p>Your recordings and notes stay under your control.</p></div></div><div className="settings-list"><button onClick={onBackup}><span><Download/><span><b>Back up all meetings</b><small>Download a portable JSON archive.</small></span></span><span>Download</span></button><label><span><Upload/><span><b>Restore a backup</b><small>Merge meetings from a saved archive.</small></span></span><span>Choose file</span><input type="file" accept="application/json,.json" onChange={onRestore}/></label>{installAvailable&&<button onClick={onInstall}><span><Smartphone/><span><b>Install Said and Done</b><small>Add the app to your home screen.</small></span></span><span>Install</span></button>}</div></section>
  <section className="settings-section compact"><div className="settings-section-heading"><ShieldCheck/><div><h3>Privacy and connection</h3><p>{session?'Cloud sync is protected by your account.':'Meetings are currently stored only on this device.'}</p></div><span className={online?'connection online':'connection'}>{online?<Wifi/>:<WifiOff/>}{online?'Online':'Offline'}</span></div></section>
 </div></div></div>
}

function App(){
 const[meetings,setMeetings]=useState<Meeting[]>(load);const[selected,setSelected]=useState(meetings[0]?.id||'');const[session,setSession]=useState<Session|null>(loadSession);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authMode,setAuthMode]=useState<'signin'|'signup'>('signin');const[cloudStatus,setCloudStatus]=useState('');const[recording,setRecording]=useState(false);const[paused,setPaused]=useState(false);const[consent,setConsent]=useState(false);const[language,setLanguage]=useState('auto');const[elapsed,setElapsed]=useState(0);const[live,setLive]=useState('');const[query,setQuery]=useState('');const[playing,setPlaying]=useState(false);const[processing,setProcessing]=useState('');const[error,setError]=useState('');const[question,setQuestion]=useState('');const[answer,setAnswer]=useState('');const[showArchived,setShowArchived]=useState(false);const[folderFilter,setFolderFilter]=useState('all');const[showDashboard,setShowDashboard]=useState(false);const[online,setOnline]=useState(navigator.onLine);const[installPrompt,setInstallPrompt]=useState<any>(null);const[settingsOpen,setSettingsOpen]=useState(false);const[libraryOpen,setLibraryOpen]=useState(false);const[mobileView,setMobileView]=useState<'home'|'detail'|'record'>('home');const[mobileTab,setMobileTab]=useState<MobileTab>('conversations');const[theme,setTheme]=useState<Theme>(()=>(localStorage.getItem('meeting-notes-theme') as Theme)||'system');const[autoSync,setAutoSync]=useState(()=>localStorage.getItem('meeting-notes-auto-sync')==='true');const media=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const recognition=useRef<any>(null);const wakeLock=useRef<any>(null);const timer=useRef<number|undefined>();
 useEffect(()=>{localStorage.setItem(storeKey,JSON.stringify(meetings))},[meetings]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')},[]);
 useEffect(()=>{const yes=()=>setOnline(true),no=()=>setOnline(false),install=(event:any)=>{event.preventDefault();setInstallPrompt(event)};window.addEventListener('online',yes);window.addEventListener('offline',no);window.addEventListener('beforeinstallprompt',install);return()=>{window.removeEventListener('online',yes);window.removeEventListener('offline',no);window.removeEventListener('beforeinstallprompt',install)}},[]);
 useEffect(()=>{session?localStorage.setItem(sessionKey,JSON.stringify(session)):localStorage.removeItem(sessionKey)},[session]);
 useEffect(()=>{localStorage.setItem('meeting-notes-theme',theme);document.documentElement.dataset.theme=theme;if(theme==='system')delete document.documentElement.dataset.resolvedTheme;else document.documentElement.dataset.resolvedTheme=theme},[theme]);
 useEffect(()=>{localStorage.setItem('meeting-notes-auto-sync',String(autoSync))},[autoSync]);
 useEffect(()=>{if(!autoSync||!session)return;const id=window.setTimeout(()=>void syncCloud(),1800);return()=>window.clearTimeout(id)},[meetings,autoSync,session]);
 const current=selected==='__recording__'?undefined:meetings.find(m=>m.id===selected)||meetings[0];
 const folders=useMemo(()=>[...new Set(meetings.map(m=>m.folder?.trim()).filter(Boolean) as string[])].sort(),[meetings]);
 const filtered=useMemo(()=>meetings.filter(m=>!!m.archived===showArchived&&(folderFilter==='all'||(m.folder||'Unfiled')===folderFilter)&&(m.title+' '+m.transcript+' '+m.summary+' '+m.actions.join(' ')+' '+(m.tags||[]).join(' ')+' '+(m.attendees||'')+' '+(m.agenda||'')+' '+(m.notes||'')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(!!b.favorite)-Number(!!a.favorite)||+new Date(b.date)-+new Date(a.date)),[meetings,query,showArchived,folderFilter]);
 const stats=useMemo(()=>{const active=meetings.filter(m=>!m.archived&&m.id!=='welcome');const actions=active.flatMap(m=>m.actions.map((task,i)=>({task,done:!!m.completed?.[i]})));return{meetings:active.length,minutes:Math.round(active.reduce((n,m)=>n+m.duration,0)/60),words:active.reduce((n,m)=>n+m.transcript.split(/\s+/).filter(Boolean).length,0),open:actions.filter(x=>!x.done).length,done:actions.filter(x=>x.done).length}},[meetings]);
 function newMeeting(){const m:Meeting={id:crypto.randomUUID(),title:'Untitled meeting',date:new Date().toISOString(),duration:0,language,meetingType:'general',status:'planned',transcript:'',summary:'',actions:[],actionDetails:[],completed:[],tags:[]};setMeetings(v=>[m,...v]);setSelected(m.id);setShowArchived(false);setShowDashboard(false)}
 function startMobileMeeting(){setSelected('__recording__');setConsent(false);setElapsed(0);setLive('');setError('');setMobileView('record')}
 function scheduleMobileMeeting(){newMeeting();setMobileView('detail')}
 function leaveMobileRecorder(){if(recording){setError('Stop the recording before leaving this screen.');return}setConsent(false);setSelected(meetings[0]?.id||'');setMobileView('home')}
 function openMobileMeeting(id:string){setSelected(id);setShowDashboard(false);setMobileView('detail')}
 async function installApp(){if(!installPrompt)return;await installPrompt.prompt();setInstallPrompt(null)}
 async function start(){if(!consent){setError('Confirm that everyone has agreed to the recording.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const mr=new MediaRecorder(stream);media.current=mr;mr.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);const size=chunks.current.reduce((n,b)=>n+b.size,0);if(size>=23*1024*1024){setError('Recording stopped at the safe upload limit.');stop()}};mr.onerror=()=>stop();mr.start(1000);setLive('');setElapsed(0);setPaused(false);setRecording(true);try{wakeLock.current=await(navigator as any).wakeLock?.request('screen')}catch{}timer.current=window.setInterval(()=>setElapsed(v=>v+1),1000);await new Promise(requestAnimationFrame);const isiPhone=/iPhone|iPad|iPod/i.test(navigator.userAgent);const SR=!isiPhone&&((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition);if(SR){try{const r=new SR();r.continuous=true;r.interimResults=true;r.onresult=(e:any)=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';setLive(text.trim())};r.onerror=()=>{};r.start();recognition.current=r}catch{recognition.current=null}}}catch{setRecording(false);alert('Microphone access is required to record a meeting.')}}
 async function analyzeMeeting(m:Meeting){setProcessing('Generating AI meeting notes…');const response=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:m.title,transcript:m.transcript,meetingType:m.meetingType||'general'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Analysis failed');const updated={...m,summary:data.summary,actions:data.action_items.map((x:ActionItem)=>x.task),actionDetails:data.action_items,keyPoints:data.key_points,decisions:data.decisions,topics:data.topics,followUp:data.follow_up,openQuestions:data.open_questions,risks:data.risks};setMeetings(v=>v.map(x=>x.id===m.id?updated:x));return updated}
 async function processAudio(blob:Blob,m:Meeting){try{setError('');setProcessing('Transcribing recording…');const form=new FormData();form.append('audio',blob,`meeting.${blob.type.includes('mp4')?'mp4':'webm'}`);form.append('language',m.language||language);const response=await fetch('/api/transcribe',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'Transcription failed');const segments:TranscriptSegment[]=Array.isArray(data.segments)?data.segments.filter((x:any)=>x&&typeof x.text==='string').map((x:any)=>({speaker:String(x.speaker||'Speaker'),text:String(x.text),start:Number(x.start)||0,end:Number(x.end)||0})):[];const withTranscript={...m,transcript:data.transcript,transcriptSegments:segments,duration:m.duration||Math.round(Number(data.duration)||0)};setMeetings(v=>v.map(x=>x.id===m.id?withTranscript:x));await analyzeMeeting(withTranscript)}catch(e){setError(e instanceof Error?e.message:'AI processing failed')}finally{setProcessing('')}}
 function stop(){const mr=media.current;if(!mr){setRecording(false);return}const finish=()=>{const blob=new Blob(chunks.current,{type:mr.mimeType||'audio/webm'});const audio=blob.size?URL.createObjectURL(blob):undefined;const text=live.trim();const result=summarize(text);const m:Meeting={id:crypto.randomUUID(),title:`Meeting ${new Date().toLocaleDateString()}`,date:new Date().toISOString(),duration:elapsed,language,status:'complete',transcript:text||'Processing audio…',summary:text?result.summary:'Your AI summary will appear after transcription.',actions:result.actions,audio};setMeetings(v=>[m,...v]);setSelected(m.id);setMobileView('detail');media.current=null;if(blob.size)void processAudio(blob,m)};mr.onstop=finish;try{if(mr.state!=='inactive')mr.stop();else finish()}catch{finish()}mr.stream.getTracks().forEach(t=>t.stop());try{recognition.current?.stop()}catch{}recognition.current=null;clearInterval(timer.current);try{wakeLock.current?.release()}catch{}wakeLock.current=null;setPaused(false);setRecording(false)}
 function pauseRecording(){const mr=media.current;if(!mr)return;try{if(mr.state==='recording'){mr.pause();setPaused(true);clearInterval(timer.current)}else if(mr.state==='paused'){mr.resume();setPaused(false);timer.current=window.setInterval(()=>setElapsed(v=>v+1),1000)}}catch{setError('Pause or resume is not supported on this browser.')}}
 function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>24*1024*1024){setError('Choose an audio file smaller than 24 MB.');return}const m:Meeting={id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,''),date:new Date().toISOString(),duration:0,transcript:'Processing audio…',summary:'Creating AI meeting notes…',actions:[],audio:URL.createObjectURL(file)};setMeetings(v=>[m,...v]);setSelected(m.id);void processAudio(file,m);e.target.value=''}
 async function authenticate(){try{setError('');setCloudStatus(authMode==='signup'?'Creating account…':'Signing in…');const path=authMode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const response=await fetch(SB_URL+path,{method:'POST',headers:{apikey:SB_KEY,'content-type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.msg||data.error_description||'Sign-in failed');if(!data.access_token){setCloudStatus('Check your email to confirm your account, then sign in.');return}setSession(data);setPassword('');setCloudStatus('Signed in. Loading cloud meetings…');await loadCloud(data)}catch(e){setError(e instanceof Error?e.message:'Sign-in failed');setCloudStatus('')}}
 async function loadCloud(active=session){if(!active)return;try{setCloudStatus('Loading cloud meetings…');const response=await fetch(SB_URL+'/rest/v1/mn_meetings?select=*&order=created_at.desc',{headers:{apikey:SB_KEY,Authorization:'Bearer '+active.access_token}});const rows=await response.json();if(!response.ok)throw new Error(rows.message||'Cloud load failed');const cloud:Meeting[]=rows.map((r:any)=>({id:r.id,title:r.title,date:r.started_at||r.created_at,duration:r.duration_seconds,transcript:r.transcript,summary:r.summary,actions:r.metadata?.actions||[],actionDetails:r.metadata?.actionDetails||[],keyPoints:r.metadata?.keyPoints||[],decisions:r.decisions||[],topics:r.key_topics||[],followUp:r.follow_up_agenda||[],openQuestions:r.open_questions||[],risks:r.risks||[],meetingType:r.meeting_type||'general',language:r.language||'auto',tags:r.metadata?.tags||[],completed:r.metadata?.completed||[],favorite:!!r.metadata?.favorite,transcriptSegments:r.metadata?.transcriptSegments||[],speakerNames:r.metadata?.speakerNames||{},attendees:r.metadata?.attendees||'',agenda:r.metadata?.agenda||'',folder:r.metadata?.folder||'',notes:r.metadata?.notes||'',followupEmail:r.metadata?.followupEmail||'',archived:!!r.metadata?.archived,status:r.status==='planned'?'planned':'complete'}));if(cloud.length){setMeetings(v=>{const map=new Map(v.map(x=>[x.id,x]));cloud.forEach(x=>map.set(x.id,x));return[...map.values()].sort((a,b)=>+new Date(b.date)-+new Date(a.date))});setSelected(cloud[0].id)}setCloudStatus('Cloud sync ready')}catch(e){setError(e instanceof Error?e.message:'Cloud load failed');setCloudStatus('')}}
 async function syncCloud(){if(!session)return;try{setCloudStatus('Syncing…');const valid=meetings.filter(m=>m.id!=='welcome');if(!valid.length){setCloudStatus('Nothing to sync yet');return}const rows=valid.map(m=>({id:m.id,user_id:session.user.id,title:m.title,meeting_type:m.meetingType||'general',status:m.status||'complete',language:m.language==='auto'?'en':m.language||'en',started_at:m.date,duration_seconds:m.duration,transcript:m.transcript,summary:m.summary,decisions:m.decisions||[],open_questions:m.openQuestions||[],risks:m.risks||[],follow_up_agenda:m.followUp||[],key_topics:m.topics||[],source:'pwa',metadata:{actions:m.actions,actionDetails:m.actionDetails,keyPoints:m.keyPoints,tags:m.tags||[],completed:m.completed||[],favorite:!!m.favorite,transcriptSegments:m.transcriptSegments||[],speakerNames:m.speakerNames||{},attendees:m.attendees||'',agenda:m.agenda||'',folder:m.folder||'',notes:m.notes||'',followupEmail:m.followupEmail||'',archived:!!m.archived}}));const response=await fetch(SB_URL+'/rest/v1/mn_meetings?on_conflict=id',{method:'POST',headers:{apikey:SB_KEY,Authorization:'Bearer '+session.access_token,'content-type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify(rows)});if(!response.ok){const data=await response.json();throw new Error(data.message||'Sync failed')}setCloudStatus('Synced across devices')}catch(e){setError(e instanceof Error?e.message:'Sync failed');setCloudStatus('')}}
 function signOut(){setSession(null);setCloudStatus('');setPassword('')}
 function update(p:Partial<Meeting>){if(!current)return;setMeetings(v=>v.map(m=>m.id===current.id?{...m,...p}:m))}
 async function regenerate(){if(!current)return;try{setError('');await analyzeMeeting(current)}catch(e){setError(e instanceof Error?e.message:'Analysis failed');const r=summarize(current.transcript);update(r)}finally{setProcessing('')}}
 async function ask(){if(!current||!question.trim())return;try{setProcessing('Searching this meeting…');setError('');const response=await fetch('/api/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,transcript:current.transcript,summary:current.summary})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Question failed');setAnswer(data.answer)}catch(e){setError(e instanceof Error?e.message:'Question failed')}finally{setProcessing('')}}
 function renameSpeaker(speaker:string,name:string){if(!current)return;update({speakerNames:{...(current.speakerNames||{}),[speaker]:name}})}
 function addAction(){if(!current)return;update({actions:[...current.actions,'New action item'],actionDetails:[...(current.actionDetails||[]),{task:'New action item',owner:null,due:null,priority:'medium'}],completed:[...(current.completed||[]),false]})}
 function updateActionDetail(i:number,patch:Partial<ActionItem>){if(!current)return;const details=current.actions.map((task,n)=>({...({task,owner:null,due:null,priority:'medium'} as ActionItem),...(current.actionDetails?.[n]||{}),task}));details[i]={...details[i],...patch};update({actionDetails:details})}
 function removeAction(i:number){if(!current)return;update({actions:current.actions.filter((_,n)=>n!==i),actionDetails:current.actionDetails?.filter((_,n)=>n!==i),completed:(current.completed||[]).filter((_,n)=>n!==i)})}
 function toggleAction(i:number){if(!current)return;const next=[...(current.completed||[])];next[i]=!next[i];update({completed:next})}
 function addTag(value:string){if(!current)return;const tag=value.trim().replace(/^#/,'');if(!tag)return;update({tags:[...new Set([...(current.tags||[]),tag])]})}
 function backupLibrary(){downloadFile('meeting-notes-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({version:1,exportedAt:new Date().toISOString(),meetings},null,2),'application/json')}
 async function restoreBackup(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const incoming=Array.isArray(parsed)?parsed:parsed.meetings;if(!Array.isArray(incoming))throw new Error('This is not a Said and Done backup.');const valid:Meeting[]=incoming.filter((m:any)=>m&&typeof m.id==='string'&&typeof m.title==='string'&&typeof m.transcript==='string').map((m:any)=>({...m,actions:Array.isArray(m.actions)?m.actions:[],date:m.date||new Date().toISOString(),duration:Number(m.duration)||0,summary:m.summary||''}));if(!valid.length)throw new Error('No meetings were found in this backup.');setMeetings(existing=>{const map=new Map(existing.map(m=>[m.id,m]));valid.forEach(m=>map.set(m.id,m));return[...map.values()]});setSelected(valid[0].id);setCloudStatus(`Restored ${valid.length} meeting${valid.length===1?'':'s'}`)}catch(err){setError(err instanceof Error?err.message:'Backup restore failed')}finally{e.target.value=''}}
 async function shareMeeting(){if(!current)return;const text=`${current.title}\n\n${current.summary}\n\nAction items:\n${current.actions.map((x,i)=>`${current.completed?.[i]?'✓':'•'} ${x}`).join('\n')}`;try{if(navigator.share)await navigator.share({title:current.title,text});else{await navigator.clipboard.writeText(text);setCloudStatus('Meeting notes copied')}}catch{}}
 function archiveMeeting(){if(!current||current.id==='welcome')return;update({archived:true});const next=meetings.find(m=>m.id!==current.id&&!m.archived);setSelected(next?.id||'welcome')}
 function restoreMeeting(){if(!current)return;update({archived:false});setShowArchived(false)}
 function deleteForever(){if(!current||!confirm('Permanently delete this meeting? This cannot be undone.'))return;const next=meetings.filter(m=>m.id!==current.id);setMeetings(next);setSelected(next.find(m=>!!m.archived===showArchived)?.id||next[0]?.id||'')}
 function downloadFile(name:string,body:string,type='text/plain'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function exportMeeting(format:'txt'|'md'|'json'|'csv'|'ics'){if(!current)return;const section=(name:string,items?:string[])=>items?.length?`\n\n${name.toUpperCase()}\n${items.map(x=>'• '+x).join('\n')}`:'';const text=`${current.title}\n${new Date(current.date).toLocaleString()}\nType: ${current.meetingType||'general'}\nAttendees: ${current.attendees||'Not listed'}\n\nSUMMARY\n${current.summary}${section('Key points',current.keyPoints)}${section('Decisions',current.decisions)}${section('Action items',current.actions)}${section('Open questions',current.openQuestions)}${section('Risks',current.risks)}${section('Follow-up agenda',current.followUp)}\n\nNOTES\n${current.notes||''}\n\nTRANSCRIPT\n${current.transcript}`;const base=safeName(current.title);if(format==='txt')downloadFile(base+'.txt',text);if(format==='md')downloadFile(base+'.md',`# ${current.title}\n\n**Date:** ${new Date(current.date).toLocaleString()}  \n**Type:** ${current.meetingType||'general'}  \n**Attendees:** ${current.attendees||'Not listed'}\n\n## Summary\n${current.summary}${section('Key points',current.keyPoints)}${section('Decisions',current.decisions)}${section('Action items',current.actions)}\n\n## Transcript\n${current.transcript}`,'text/markdown');if(format==='json')downloadFile(base+'.json',JSON.stringify(current,null,2),'application/json');if(format==='csv'){const esc=(v:string)=>'"'+v.replace(/"/g,'""')+'"';const rows=['Task,Owner,Due,Priority,Completed',...current.actions.map((task,i)=>[task,current.actionDetails?.[i]?.owner||'',current.actionDetails?.[i]?.due||'',current.actionDetails?.[i]?.priority||'',current.completed?.[i]?'Yes':'No'].map(v=>esc(String(v))).join(','))];downloadFile(base+'-actions.csv',rows.join('\n'),'text/csv')}if(format==='ics'){const start=new Date(current.date),end=new Date(start.getTime()+Math.max(current.duration,1800)*1000),icsDate=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const clean=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Said and Done//EN\r\nBEGIN:VEVENT\r\nUID:${current.id}@meeting-notes\r\nDTSTAMP:${icsDate(new Date())}\r\nDTSTART:${icsDate(start)}\r\nDTEND:${icsDate(end)}\r\nSUMMARY:${clean(current.title)}\r\nDESCRIPTION:${clean(current.agenda||current.summary||'Meeting')}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;downloadFile(base+'.ics',ics,'text/calendar')}}
 async function copyNotes(){if(!current)return;await navigator.clipboard.writeText(`${current.title}\n\n${current.summary}\n\nAction items:\n${current.actions.map(x=>'• '+x).join('\n')}`);setCloudStatus('Notes copied')}
 function printMeeting(){window.print()}
 async function draftFollowup(){if(!current)return;try{setProcessing('Drafting follow-up email…');setError('');const response=await fetch('/api/followup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:current.title,attendees:current.attendees,summary:current.summary,actions:current.actions,decisions:current.decisions,openQuestions:current.openQuestions})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Follow-up draft failed');update({followupEmail:data.email})}catch(e){const actions=current.actions.length?'\n\nAction items:\n'+current.actions.map((x,i)=>'• '+x+(current.actionDetails?.[i]?.owner?' ('+current.actionDetails[i].owner+')':'')).join('\n'):'';const decisions=current.decisions?.length?'\n\nDecisions:\n'+current.decisions.map(x=>'• '+x).join('\n'):'';update({followupEmail:'Subject: '+current.title+' follow-up\n\nHi everyone,\n\nHere is a recap of '+current.title+'.\n\n'+current.summary+decisions+actions+'\n\nPlease reply with any corrections or questions.\n\nBest,'});setError((e instanceof Error?e.message:'AI drafting is unavailable')+' A basic local draft was created.')}finally{setProcessing('')}}
 return <main>
  {libraryOpen&&<button className="library-backdrop" aria-label="Close meeting library" onClick={()=>setLibraryOpen(false)}/>}<aside className={libraryOpen?'mobile-open':''}><div className="brand"><span className="logo"><img src="/saiddone-mark.png" alt=""/></span><div><b>Said and Done</b><small>From conversation to completion</small></div><button className="sidebar-close" onClick={()=>setLibraryOpen(false)} aria-label="Close meeting library"><X/></button></div><button className="new-meeting" onClick={()=>{newMeeting();setLibraryOpen(false)}}><Plus/> New meeting</button><div className="sidebar-nav"><button className={showDashboard?'active':''} onClick={()=>{setShowDashboard(v=>!v);setLibraryOpen(false)}}><BarChart3/> Insights</button><button className={showArchived?'active':''} onClick={()=>{setShowArchived(v=>!v);setFolderFilter('all')}}><Archive/> {showArchived?'Active':'Archive'}</button></div><div className="search"><Search/><input aria-label="Search meetings" placeholder="Search your meetings" value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="folder-filter"><Folder/><select aria-label="Filter by folder" value={folderFilter} onChange={e=>setFolderFilter(e.target.value)}><option value="all">All folders</option><option value="Unfiled">Unfiled</option>{folders.map(folder=><option key={folder}>{folder}</option>)}</select></label><div className="meeting-list">{filtered.length?filtered.map(m=><button className={m.id===selected?'active':''} onClick={()=>{setSelected(m.id);setShowDashboard(false);setLibraryOpen(false)}} key={m.id}><span>{m.title}</span><small>{m.status==='planned'?'Planned · ':''}{new Date(m.date).toLocaleDateString()} · {fmt(m.duration)}</small></button>):<p className="empty-list">No {showArchived?'archived ':''}meetings found.</p>}</div><button className="settings-entry" onClick={()=>setSettingsOpen(true)}><Settings/><span><b>Settings</b><small>{session?'Cloud sync connected':'Local workspace'}</small></span></button></aside>
  {mobileView==='home'&&<MobileHome meetings={meetings} query={query} tab={mobileTab} onQuery={setQuery} onTab={setMobileTab} onOpenMeeting={openMobileMeeting} onRecord={startMobileMeeting} onSchedule={scheduleMobileMeeting} onSettings={()=>setSettingsOpen(true)}/>}<section className={`workspace ${mobileView==='home'?'mobile-editor-hidden':mobileView==='record'?'mobile-record-view':'mobile-detail-view'}`}><div className="mobile-appbar"><button className="mobile-back" onClick={mobileView==='record'?leaveMobileRecorder:()=>setMobileView('home')}>{mobileView==='record'?<X/>:<ChevronLeft/>}<span>{mobileView==='record'?'Cancel':'Conversations'}</span></button><button className="icon-button" onClick={()=>setSettingsOpen(true)} aria-label="Open settings"><Settings/></button></div><header><div>{current?<div className="title-row"><input className="title-input" aria-label="Meeting title" value={current.title} onChange={e=>update({title:e.target.value})}/><button className={current.favorite?'star active':'star'} aria-label="Favorite meeting" onClick={()=>update({favorite:!current.favorite})}><Star/></button></div>:<h1>New meeting</h1>}<p>{current?new Date(current.date).toLocaleString():'Start your first recording'}</p></div><div className="header-actions"><button className="ghost" onClick={()=>void shareMeeting()}><Share2/> Share</button><button className="ghost" onClick={()=>void copyNotes()}><Copy/> Copy</button><details className="export-menu"><summary><Download/> Export</summary><div><button onClick={()=>exportMeeting('txt')}>Text</button><button onClick={()=>exportMeeting('md')}>Markdown</button><button onClick={()=>exportMeeting('json')}>JSON backup</button><button onClick={()=>exportMeeting('csv')}>Action items CSV</button><button onClick={()=>exportMeeting('ics')}><CalendarPlus/> Calendar event</button><button onClick={printMeeting}><Printer/> Print or PDF</button></div></details>{current?.archived?<><button className="ghost" onClick={restoreMeeting}><RotateCcw/> Restore</button><button className="ghost danger" aria-label="Delete forever" onClick={deleteForever}><Trash2/></button></>:current?.status==='planned'?<button className="ghost danger" onClick={deleteForever}><Trash2/> Delete</button>:<button className="ghost danger" aria-label="Archive meeting" onClick={archiveMeeting}><Archive/></button>}</div></header>
   {showDashboard&&<section className="dashboard"><div><b>{stats.meetings}</b><span>Meetings</span></div><div><b>{stats.minutes}</b><span>Minutes recorded</span></div><div><b>{stats.words.toLocaleString()}</b><span>Transcript words</span></div><div><b>{stats.open}</b><span>Open actions</span></div><div><b>{stats.done}</b><span>Completed actions</span></div></section>}<div className="meeting-controls"><label>Meeting type<select value={current?.meetingType||'general'} onChange={e=>update({meetingType:e.target.value})}><option value="general">General</option><option value="one-on-one">1:1</option><option value="project">Project update</option><option value="client">Client meeting</option><option value="interview">Interview</option><option value="brainstorm">Brainstorm</option><option value="training">Training</option></select></label><label>Language<select value={current?.language||language} onChange={e=>{setLanguage(e.target.value);if(current)update({language:e.target.value})}}><option value="auto">Auto detect</option><option value="en">English</option><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option><option value="pt">Portuguese</option><option value="it">Italian</option><option value="ja">Japanese</option><option value="ko">Korean</option><option value="zh">Chinese</option></select></label><label>Status<select value={current?.status||'complete'} onChange={e=>update({status:e.target.value as 'planned'|'complete'})}><option value="planned">Planned</option><option value="complete">Complete</option></select></label><span>AI tailors notes to this format.</span></div>{current&&<details className="meeting-meta" open={current.status==='planned'}><summary>Meeting details</summary><div><label>Date and time<input type="datetime-local" value={localDateTime(current.date)} onChange={e=>update({date:new Date(e.target.value).toISOString()})}/></label><label>Folder<input value={current.folder||''} placeholder="Example: Client meetings" list="meeting-folders" onChange={e=>update({folder:e.target.value})}/><datalist id="meeting-folders">{folders.map(folder=><option key={folder} value={folder}/>)}</datalist></label><label className="wide">Attendees<input value={current.attendees||''} placeholder="Names or email addresses" onChange={e=>update({attendees:e.target.value})}/></label><label className="wide">Agenda<textarea value={current.agenda||''} placeholder="What should this meeting cover?" onChange={e=>update({agenda:e.target.value})}/></label><label className="wide">Private notes<textarea value={current.notes||''} placeholder="Add context or personal notes" onChange={e=>update({notes:e.target.value})}/></label></div></details>}
   <label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I confirmed that participants agreed to this recording.</span></label>
   <div className="recorder"><div className={`pulse ${recording?'on':''}`}><Mic/></div><div><b>{recording?'Listening…':'Ready to record'}</b><span>{recording?fmt(elapsed):'Capture audio and live transcript'}</span></div>{recording?<><button className="pause" onClick={pauseRecording}>{paused?<Play/>:<Pause/>} {paused?'Resume':'Pause'}</button><button className="stop" onClick={stop}><Square/> Stop</button></>:<button className="record" onClick={start} disabled={!consent}><Mic/> Record</button>}<label className="upload"><Upload/> Import<input type="file" accept="audio/*,video/*" onChange={upload}/></label></div>
   {recording&&<><div className="mobile-record-controls"><button onClick={pauseRecording}>{paused?<Play/>:<Pause/>} {paused?'Resume':'Pause'}</button><button className="mobile-stop" onClick={stop}><Square/> Stop recording · {fmt(elapsed)}</button></div><div className="live"><span>{paused?'RECORDING PAUSED':(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'RECORDING AUDIO':'LIVE TRANSCRIPT')}</span><p>{live||(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'Recording safely. Add or paste the transcript when you finish.':'Start speaking. Your transcript will appear here.')}</p></div></>}
   {processing&&<div className="status ai-status">{processing}</div>}{error&&<div className="status error-status">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
   {current&&<><div className="grid"><article><div className="section-title"><FileText/><h2>Summary</h2><button onClick={regenerate}>Generate summary</button></div><textarea aria-label="Meeting summary" value={current.summary} onChange={e=>update({summary:e.target.value})}/></article><article><div className="section-title"><ListChecks/><h2>Action items</h2><button onClick={addAction}><Plus/> Add</button></div><div className="actions">{current.actions.length?current.actions.map((a,i)=><div className={current.completed?.[i]?'action-card done':'action-card'} key={i}><input aria-label={"Complete "+a} type="checkbox" checked={!!current.completed?.[i]} onChange={()=>toggleAction(i)}/><div><span className="action-task" contentEditable suppressContentEditableWarning onBlur={e=>{const task=e.currentTarget.textContent||'';const n=[...current.actions];n[i]=task;update({actions:n});updateActionDetail(i,{task})}}>{a}</span><div className="action-fields"><input aria-label="Action owner" value={current.actionDetails?.[i]?.owner||''} placeholder="Owner" onChange={e=>updateActionDetail(i,{owner:e.target.value||null})}/><input aria-label="Action due date" type="date" value={current.actionDetails?.[i]?.due||''} onChange={e=>updateActionDetail(i,{due:e.target.value||null})}/><select aria-label="Action priority" value={current.actionDetails?.[i]?.priority||'medium'} onChange={e=>updateActionDetail(i,{priority:e.target.value as 'low'|'medium'|'high'})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div></div><button className="remove-action" aria-label="Remove action item" onClick={()=>removeAction(i)}><X/></button></div>):<span>No supported action items were identified.</span>}</div></article></div>
   <article className="organize"><div className="section-title"><Tag/><h2>Topics and tags</h2></div><div className="tag-list">{[...(current.topics||[]),...(current.tags||[])].filter((x,i,a)=>a.indexOf(x)===i).map((x,i)=><span key={i}>#{x}{current.tags?.includes(x)&&<button aria-label={"Remove "+x} onClick={()=>update({tags:current.tags?.filter(t=>t!==x)})}><X/></button>}</span>)}</div><form className="tag-form" onSubmit={e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('tag') as HTMLInputElement;addTag(input.value);input.value=''}}><input name="tag" placeholder="Add a tag"/><button>Add tag</button></form></article>
   {current.audio&&<div className="player"><button onClick={()=>{const el=document.querySelector('audio')!;playing?el.pause():el.play();setPlaying(!playing)}}>{playing?<Pause/>:<Play/>}</button><audio src={current.audio} onEnded={()=>setPlaying(false)}/><div><b>Meeting audio</b><span>Playback stored for this session</span></div></div>}
   {(current.keyPoints?.length||current.decisions?.length)&&<div className="grid insights"><article><div className="section-title"><FileText/><h2>Key points</h2></div><ul>{current.keyPoints?.map((x,i)=><li key={i}>{x}</li>)}</ul></article><article><div className="section-title"><ListChecks/><h2>Decisions</h2></div>{current.decisions?.length?<ul>{current.decisions.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>No explicit decisions identified.</p>}</article></div>}
   {(current.openQuestions?.length||current.risks?.length||current.followUp?.length)&&<div className="intelligence-grid"><article><div className="section-title"><Search/><h2>Open questions</h2></div>{current.openQuestions?.length?<ul>{current.openQuestions.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>None identified.</p>}</article><article><div className="section-title"><ShieldCheck/><h2>Risks</h2></div>{current.risks?.length?<ul>{current.risks.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>None identified.</p>}</article><article><div className="section-title"><Clock/><h2>Next meeting</h2></div>{current.followUp?.length?<ul>{current.followUp.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>No follow-up agenda needed.</p>}</article></div>}
   <article className="followup-email"><div className="section-title"><Mail/><h2>Follow-up email</h2><button onClick={()=>void draftFollowup()} disabled={!current.summary||!!processing}>{current.followupEmail?'Regenerate':'Draft email'}</button></div>{current.followupEmail?<><textarea aria-label="Follow-up email draft" value={current.followupEmail} onChange={e=>update({followupEmail:e.target.value})}/><button className="copy-email" onClick={()=>navigator.clipboard.writeText(current.followupEmail||'')}><Copy/> Copy email</button></>:<p>Turn the summary, decisions, and action items into a ready-to-send recap.</p>}</article>
   <article className="ask"><div className="section-title"><Search/><h2>Ask this meeting</h2></div><div className="ask-row"><input placeholder="What was decided? Who owns the follow-up?" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void ask()}}/><button onClick={()=>void ask()} disabled={!question.trim()||!!processing}>Ask</button></div>{answer&&<p className="answer">{answer}</p>}</article>
   <article className="transcript"><div className="section-title"><Clock/><h2>Transcript</h2><span>{current.transcript.split(/\s+/).filter(Boolean).length} words</span></div>{current.transcriptSegments?.length?<details className="speaker-transcript" open><summary>Speaker timeline · {new Set(current.transcriptSegments.map(s=>s.speaker)).size} speakers</summary><div className="speaker-names">{[...new Set(current.transcriptSegments.map(s=>s.speaker))].map(speaker=><label key={speaker}><span>{speaker.replace(/_/g,' ')}</span><input aria-label={"Rename "+speaker} value={current.speakerNames?.[speaker]||''} placeholder={"Name "+speaker.replace(/_/g,' ')} onChange={e=>renameSpeaker(speaker,e.target.value)}/></label>)}</div><div className="speaker-segments">{current.transcriptSegments.map((segment,i)=><div className="speaker-segment" key={i}><b>{current.speakerNames?.[segment.speaker]?.trim()||segment.speaker.replace(/_/g,' ')}</b><time>{fmt(Math.round(segment.start))}</time><p>{segment.text}</p></div>)}</div></details>:null}<label className="editable-transcript"><span>{current.transcriptSegments?.length?'Editable transcript':'Meeting transcript'}</span><textarea aria-label="Meeting transcript" value={current.transcript} onChange={e=>update({transcript:e.target.value})}/></label></article></>}
  </section><SettingsPanel open={settingsOpen} onClose={()=>setSettingsOpen(false)} session={session} email={email} password={password} authMode={authMode} cloudStatus={cloudStatus} online={online} installAvailable={!!installPrompt} theme={theme} autoSync={autoSync} onEmail={setEmail} onPassword={setPassword} onAuthMode={()=>setAuthMode(authMode==='signin'?'signup':'signin')} onAuthenticate={()=>void authenticate()} onSync={()=>void syncCloud()} onSignOut={signOut} onBackup={backupLibrary} onRestore={e=>void restoreBackup(e)} onInstall={()=>void installApp()} onTheme={setTheme} onAutoSync={setAutoSync}/>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
