import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Mic,Square,Upload,Search,FileText,ListChecks,Clock,Trash2,Download,ShieldCheck,Play,Pause}from'lucide-react';
import'./styles.css';

type Meeting={id:string;title:string;date:string;duration:number;transcript:string;summary:string;actions:string[];audio?:string};
const seed:Meeting[]=[{id:'welcome',title:'Welcome to Meeting Notes',date:new Date().toISOString(),duration:0,transcript:'Record a meeting or import an audio file. Your recordings and notes stay on this device.',summary:'A private workspace for capturing meetings, transcripts, summaries, and action items.',actions:['Record your first meeting'],}];
const storeKey='meeting-notes-v1';
const load=():Meeting[]=>{try{return JSON.parse(localStorage.getItem(storeKey)||'null')||seed}catch{return seed}};
const summarize=(text:string)=>{const sentences=text.match(/[^.!?]+[.!?]+/g)||[text];const clean=sentences.map(s=>s.trim()).filter(Boolean);const actions=clean.filter(s=>/\b(will|need to|should|follow up|action|send|review|complete|schedule|due|owner)\b/i.test(s)).slice(0,6);return{summary:clean.slice(0,3).join(' ')||'No summary available yet.',actions:actions.length?actions:['Review the transcript and add action items.']}};
const fmt=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;

function App(){
 const[meetings,setMeetings]=useState<Meeting[]>(load);const[selected,setSelected]=useState(meetings[0]?.id||'');const[recording,setRecording]=useState(false);const[elapsed,setElapsed]=useState(0);const[live,setLive]=useState('');const[query,setQuery]=useState('');const[playing,setPlaying]=useState(false);const media=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const recognition=useRef<any>(null);const timer=useRef<number|undefined>();
 useEffect(()=>{localStorage.setItem(storeKey,JSON.stringify(meetings))},[meetings]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')},[]);
 const current=meetings.find(m=>m.id===selected)||meetings[0];
 const filtered=useMemo(()=>meetings.filter(m=>(m.title+' '+m.transcript).toLowerCase().includes(query.toLowerCase())),[meetings,query]);
 async function start(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const mr=new MediaRecorder(stream);media.current=mr;mr.ondataavailable=e=>chunks.current.push(e.data);mr.start();setLive('');setElapsed(0);setRecording(true);timer.current=window.setInterval(()=>setElapsed(v=>v+1),1000);const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(SR){const r=new SR();r.continuous=true;r.interimResults=true;r.onresult=(e:any)=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';setLive(text.trim())};r.onerror=()=>{};r.start();recognition.current=r}}catch{alert('Microphone access is required to record a meeting.')}}
 function stop(){if(!media.current)return;media.current.onstop=()=>{const blob=new Blob(chunks.current,{type:media.current?.mimeType||'audio/webm'});const audio=URL.createObjectURL(blob);const text=live.trim();const result=summarize(text);const m:Meeting={id:crypto.randomUUID(),title:`Meeting ${new Date().toLocaleDateString()}`,date:new Date().toISOString(),duration:elapsed,transcript:text||'Audio captured. Live transcription was not available in this browser.',summary:result.summary,actions:result.actions,audio};setMeetings(v=>[m,...v]);setSelected(m.id)};media.current.stop();media.current.stream.getTracks().forEach(t=>t.stop());recognition.current?.stop();clearInterval(timer.current);setRecording(false)}
 function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const m:Meeting={id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,''),date:new Date().toISOString(),duration:0,transcript:'Audio imported. Play it back and add or paste the transcript below.',summary:'Imported audio is ready for review.',actions:['Add the transcript to generate meeting notes'],audio:URL.createObjectURL(file)};setMeetings(v=>[m,...v]);setSelected(m.id)}
 function update(p:Partial<Meeting>){if(!current)return;setMeetings(v=>v.map(m=>m.id===current.id?{...m,...p}:m))}
 function regenerate(){if(!current)return;const r=summarize(current.transcript);update(r)}
 function remove(){if(!current||!confirm('Delete this meeting from this device?'))return;const next=meetings.filter(m=>m.id!==current.id);setMeetings(next);setSelected(next[0]?.id||'')}
 function download(){if(!current)return;const body=`${current.title}\n${new Date(current.date).toLocaleString()}\n\nSUMMARY\n${current.summary}\n\nACTION ITEMS\n${current.actions.map(x=>'• '+x).join('\n')}\n\nTRANSCRIPT\n${current.transcript}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/plain'}));a.download=current.title+'.txt';a.click()}
 return <main>
  <aside><div className="brand"><span className="logo"><Mic/></span><div><b>Meeting Notes</b><small>Private workspace</small></div></div><div className="search"><Search/><input aria-label="Search meetings" placeholder="Search meetings" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="meeting-list">{filtered.map(m=><button className={m.id===selected?'active':''} onClick={()=>setSelected(m.id)} key={m.id}><span>{m.title}</span><small>{new Date(m.date).toLocaleDateString()} · {fmt(m.duration)}</small></button>)}</div><div className="privacy"><ShieldCheck/><span>Stored only on this device</span></div></aside>
  <section className="workspace"><header><div><h1>{current?.title||'New meeting'}</h1><p>{current?new Date(current.date).toLocaleString():'Start your first recording'}</p></div><div className="header-actions"><button className="ghost" onClick={download}><Download/> Export</button><button className="ghost danger" onClick={remove}><Trash2/></button></div></header>
   <div className="recorder"><div className={`pulse ${recording?'on':''}`}><Mic/></div><div><b>{recording?'Listening…':'Ready to record'}</b><span>{recording?fmt(elapsed):'Capture audio and live transcript'}</span></div>{recording?<button className="stop" onClick={stop}><Square/> Stop</button>:<button className="record" onClick={start}><Mic/> Record</button>}<label className="upload"><Upload/> Import<input type="file" accept="audio/*,video/*" onChange={upload}/></label></div>
   {recording&&<div className="live"><span>LIVE TRANSCRIPT</span><p>{live||'Start speaking. Your transcript will appear here.'}</p></div>}
   {current&&<><div className="grid"><article><div className="section-title"><FileText/><h2>Summary</h2><button onClick={regenerate}>Refresh</button></div><textarea aria-label="Meeting summary" value={current.summary} onChange={e=>update({summary:e.target.value})}/></article><article><div className="section-title"><ListChecks/><h2>Action items</h2></div><div className="actions">{current.actions.map((a,i)=><label key={i}><input type="checkbox"/><span contentEditable suppressContentEditableWarning onBlur={e=>{const n=[...current.actions];n[i]=e.currentTarget.textContent||'';update({actions:n})}}>{a}</span></label>)}</div></article></div>
   {current.audio&&<div className="player"><button onClick={()=>{const el=document.querySelector('audio')!;playing?el.pause():el.play();setPlaying(!playing)}}>{playing?<Pause/>:<Play/>}</button><audio src={current.audio} onEnded={()=>setPlaying(false)}/><div><b>Meeting audio</b><span>Playback stored for this session</span></div></div>}
   <article className="transcript"><div className="section-title"><Clock/><h2>Transcript</h2><span>{current.transcript.split(/\s+/).filter(Boolean).length} words</span></div><textarea aria-label="Meeting transcript" value={current.transcript} onChange={e=>update({transcript:e.target.value})}/></article></>}
  </section>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
